/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedPortalWithdrawalRouteImport } from './routes/_authenticated/portal.withdrawal'
import { Route as AuthenticatedPortalSpecialExamRegistrationRouteImport } from './routes/_authenticated/portal.special-exam-registration'
import { Route as AuthenticatedPortalResitExamsRouteImport } from './routes/_authenticated/portal.resit-exams'
import { Route as AuthenticatedPortalRegisterUnitsRouteImport } from './routes/_authenticated/portal.register-units'
import { Route as AuthenticatedPortalProvisionalTranscriptRouteImport } from './routes/_authenticated/portal.provisional-transcript'
import { Route as AuthenticatedPortalProvisionalResultsSlipRouteImport } from './routes/_authenticated/portal.provisional-results-slip'
import { Route as AuthenticatedPortalLinkProfileRouteImport } from './routes/_authenticated/portal.link-profile'
import { Route as AuthenticatedPortalGraduationClearanceRouteImport } from './routes/_authenticated/portal.graduation-clearance'
import { Route as AuthenticatedPortalFeesPaymentPdfRouteImport } from './routes/_authenticated/portal.fees-payment-pdf'
import { Route as AuthenticatedPortalFeesPaymentRouteImport } from './routes/_authenticated/portal.fees-payment'
import { Route as AuthenticatedPortalFeeStatementRouteImport } from './routes/_authenticated/portal.fee-statement'
import { Route as AuthenticatedPortalExamCardRouteImport } from './routes/_authenticated/portal.exam-card'
import { Route as AuthenticatedPortalDefermentRouteImport } from './routes/_authenticated/portal.deferment'
import { Route as AuthenticatedPortalChangePasswordRouteImport } from './routes/_authenticated/portal.change-password'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalWithdrawalRoute =
  AuthenticatedPortalWithdrawalRouteImport.update({
    id: '/portal/withdrawal',
    path: '/portal/withdrawal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalSpecialExamRegistrationRoute =
  AuthenticatedPortalSpecialExamRegistrationRouteImport.update({
    id: '/portal/special-exam-registration',
    path: '/portal/special-exam-registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalResitExamsRoute =
  AuthenticatedPortalResitExamsRouteImport.update({
    id: '/portal/resit-exams',
    path: '/portal/resit-exams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalRegisterUnitsRoute =
  AuthenticatedPortalRegisterUnitsRouteImport.update({
    id: '/portal/register-units',
    path: '/portal/register-units',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalProvisionalTranscriptRoute =
  AuthenticatedPortalProvisionalTranscriptRouteImport.update({
    id: '/portal/provisional-transcript',
    path: '/portal/provisional-transcript',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalProvisionalResultsSlipRoute =
  AuthenticatedPortalProvisionalResultsSlipRouteImport.update({
    id: '/portal/provisional-results-slip',
    path: '/portal/provisional-results-slip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalLinkProfileRoute =
  AuthenticatedPortalLinkProfileRouteImport.update({
    id: '/portal/link-profile',
    path: '/portal/link-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalGraduationClearanceRoute =
  AuthenticatedPortalGraduationClearanceRouteImport.update({
    id: '/portal/graduation-clearance',
    path: '/portal/graduation-clearance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalFeesPaymentPdfRoute =
  AuthenticatedPortalFeesPaymentPdfRouteImport.update({
    id: '/portal/fees-payment-pdf',
    path: '/portal/fees-payment-pdf',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalFeesPaymentRoute =
  AuthenticatedPortalFeesPaymentRouteImport.update({
    id: '/portal/fees-payment',
    path: '/portal/fees-payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalFeeStatementRoute =
  AuthenticatedPortalFeeStatementRouteImport.update({
    id: '/portal/fee-statement',
    path: '/portal/fee-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalExamCardRoute =
  AuthenticatedPortalExamCardRouteImport.update({
    id: '/portal/exam-card',
    path: '/portal/exam-card',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalDefermentRoute =
  AuthenticatedPortalDefermentRouteImport.update({
    id: '/portal/deferment',
    path: '/portal/deferment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalChangePasswordRoute =
  AuthenticatedPortalChangePasswordRouteImport.update({
    id: '/portal/change-password',
    path: '/portal/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/portal/change-password': typeof AuthenticatedPortalChangePasswordRoute
  '/portal/deferment': typeof AuthenticatedPortalDefermentRoute
  '/portal/exam-card': typeof AuthenticatedPortalExamCardRoute
  '/portal/fee-statement': typeof AuthenticatedPortalFeeStatementRoute
  '/portal/fees-payment': typeof AuthenticatedPortalFeesPaymentRoute
  '/portal/fees-payment-pdf': typeof AuthenticatedPortalFeesPaymentPdfRoute
  '/portal/graduation-clearance': typeof AuthenticatedPortalGraduationClearanceRoute
  '/portal/link-profile': typeof AuthenticatedPortalLinkProfileRoute
  '/portal/provisional-results-slip': typeof AuthenticatedPortalProvisionalResultsSlipRoute
  '/portal/provisional-transcript': typeof AuthenticatedPortalProvisionalTranscriptRoute
  '/portal/register-units': typeof AuthenticatedPortalRegisterUnitsRoute
  '/portal/resit-exams': typeof AuthenticatedPortalResitExamsRoute
  '/portal/special-exam-registration': typeof AuthenticatedPortalSpecialExamRegistrationRoute
  '/portal/withdrawal': typeof AuthenticatedPortalWithdrawalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/portal/change-password': typeof AuthenticatedPortalChangePasswordRoute
  '/portal/deferment': typeof AuthenticatedPortalDefermentRoute
  '/portal/exam-card': typeof AuthenticatedPortalExamCardRoute
  '/portal/fee-statement': typeof AuthenticatedPortalFeeStatementRoute
  '/portal/fees-payment': typeof AuthenticatedPortalFeesPaymentRoute
  '/portal/fees-payment-pdf': typeof AuthenticatedPortalFeesPaymentPdfRoute
  '/portal/graduation-clearance': typeof AuthenticatedPortalGraduationClearanceRoute
  '/portal/link-profile': typeof AuthenticatedPortalLinkProfileRoute
  '/portal/provisional-results-slip': typeof AuthenticatedPortalProvisionalResultsSlipRoute
  '/portal/provisional-transcript': typeof AuthenticatedPortalProvisionalTranscriptRoute
  '/portal/register-units': typeof AuthenticatedPortalRegisterUnitsRoute
  '/portal/resit-exams': typeof AuthenticatedPortalResitExamsRoute
  '/portal/special-exam-registration': typeof AuthenticatedPortalSpecialExamRegistrationRoute
  '/portal/withdrawal': typeof AuthenticatedPortalWithdrawalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/portal/change-password': typeof AuthenticatedPortalChangePasswordRoute
  '/_authenticated/portal/deferment': typeof AuthenticatedPortalDefermentRoute
  '/_authenticated/portal/exam-card': typeof AuthenticatedPortalExamCardRoute
  '/_authenticated/portal/fee-statement': typeof AuthenticatedPortalFeeStatementRoute
  '/_authenticated/portal/fees-payment': typeof AuthenticatedPortalFeesPaymentRoute
  '/_authenticated/portal/fees-payment-pdf': typeof AuthenticatedPortalFeesPaymentPdfRoute
  '/_authenticated/portal/graduation-clearance': typeof AuthenticatedPortalGraduationClearanceRoute
  '/_authenticated/portal/link-profile': typeof AuthenticatedPortalLinkProfileRoute
  '/_authenticated/portal/provisional-results-slip': typeof AuthenticatedPortalProvisionalResultsSlipRoute
  '/_authenticated/portal/provisional-transcript': typeof AuthenticatedPortalProvisionalTranscriptRoute
  '/_authenticated/portal/register-units': typeof AuthenticatedPortalRegisterUnitsRoute
  '/_authenticated/portal/resit-exams': typeof AuthenticatedPortalResitExamsRoute
  '/_authenticated/portal/special-exam-registration': typeof AuthenticatedPortalSpecialExamRegistrationRoute
  '/_authenticated/portal/withdrawal': typeof AuthenticatedPortalWithdrawalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/analytics'
    | '/audit-logs'
    | '/branches'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/invoices'
    | '/payments'
    | '/permissions'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/students'
    | '/transactions'
    | '/users'
    | '/portal/change-password'
    | '/portal/deferment'
    | '/portal/exam-card'
    | '/portal/fee-statement'
    | '/portal/fees-payment'
    | '/portal/fees-payment-pdf'
    | '/portal/graduation-clearance'
    | '/portal/link-profile'
    | '/portal/provisional-results-slip'
    | '/portal/provisional-transcript'
    | '/portal/register-units'
    | '/portal/resit-exams'
    | '/portal/special-exam-registration'
    | '/portal/withdrawal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/analytics'
    | '/audit-logs'
    | '/branches'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/invoices'
    | '/payments'
    | '/permissions'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/students'
    | '/transactions'
    | '/users'
    | '/portal/change-password'
    | '/portal/deferment'
    | '/portal/exam-card'
    | '/portal/fee-statement'
    | '/portal/fees-payment'
    | '/portal/fees-payment-pdf'
    | '/portal/graduation-clearance'
    | '/portal/link-profile'
    | '/portal/provisional-results-slip'
    | '/portal/provisional-transcript'
    | '/portal/register-units'
    | '/portal/resit-exams'
    | '/portal/special-exam-registration'
    | '/portal/withdrawal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-logs'
    | '/_authenticated/branches'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/fees'
    | '/_authenticated/invoices'
    | '/_authenticated/payments'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/transactions'
    | '/_authenticated/users'
    | '/_authenticated/portal/change-password'
    | '/_authenticated/portal/deferment'
    | '/_authenticated/portal/exam-card'
    | '/_authenticated/portal/fee-statement'
    | '/_authenticated/portal/fees-payment'
    | '/_authenticated/portal/fees-payment-pdf'
    | '/_authenticated/portal/graduation-clearance'
    | '/_authenticated/portal/link-profile'
    | '/_authenticated/portal/provisional-results-slip'
    | '/_authenticated/portal/provisional-transcript'
    | '/_authenticated/portal/register-units'
    | '/_authenticated/portal/resit-exams'
    | '/_authenticated/portal/special-exam-registration'
    | '/_authenticated/portal/withdrawal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/withdrawal': {
      id: '/_authenticated/portal/withdrawal'
      path: '/portal/withdrawal'
      fullPath: '/portal/withdrawal'
      preLoaderRoute: typeof AuthenticatedPortalWithdrawalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/special-exam-registration': {
      id: '/_authenticated/portal/special-exam-registration'
      path: '/portal/special-exam-registration'
      fullPath: '/portal/special-exam-registration'
      preLoaderRoute: typeof AuthenticatedPortalSpecialExamRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/resit-exams': {
      id: '/_authenticated/portal/resit-exams'
      path: '/portal/resit-exams'
      fullPath: '/portal/resit-exams'
      preLoaderRoute: typeof AuthenticatedPortalResitExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/register-units': {
      id: '/_authenticated/portal/register-units'
      path: '/portal/register-units'
      fullPath: '/portal/register-units'
      preLoaderRoute: typeof AuthenticatedPortalRegisterUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/provisional-transcript': {
      id: '/_authenticated/portal/provisional-transcript'
      path: '/portal/provisional-transcript'
      fullPath: '/portal/provisional-transcript'
      preLoaderRoute: typeof AuthenticatedPortalProvisionalTranscriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/provisional-results-slip': {
      id: '/_authenticated/portal/provisional-results-slip'
      path: '/portal/provisional-results-slip'
      fullPath: '/portal/provisional-results-slip'
      preLoaderRoute: typeof AuthenticatedPortalProvisionalResultsSlipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/link-profile': {
      id: '/_authenticated/portal/link-profile'
      path: '/portal/link-profile'
      fullPath: '/portal/link-profile'
      preLoaderRoute: typeof AuthenticatedPortalLinkProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/graduation-clearance': {
      id: '/_authenticated/portal/graduation-clearance'
      path: '/portal/graduation-clearance'
      fullPath: '/portal/graduation-clearance'
      preLoaderRoute: typeof AuthenticatedPortalGraduationClearanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/fees-payment-pdf': {
      id: '/_authenticated/portal/fees-payment-pdf'
      path: '/portal/fees-payment-pdf'
      fullPath: '/portal/fees-payment-pdf'
      preLoaderRoute: typeof AuthenticatedPortalFeesPaymentPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/fees-payment': {
      id: '/_authenticated/portal/fees-payment'
      path: '/portal/fees-payment'
      fullPath: '/portal/fees-payment'
      preLoaderRoute: typeof AuthenticatedPortalFeesPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/fee-statement': {
      id: '/_authenticated/portal/fee-statement'
      path: '/portal/fee-statement'
      fullPath: '/portal/fee-statement'
      preLoaderRoute: typeof AuthenticatedPortalFeeStatementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/exam-card': {
      id: '/_authenticated/portal/exam-card'
      path: '/portal/exam-card'
      fullPath: '/portal/exam-card'
      preLoaderRoute: typeof AuthenticatedPortalExamCardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/deferment': {
      id: '/_authenticated/portal/deferment'
      path: '/portal/deferment'
      fullPath: '/portal/deferment'
      preLoaderRoute: typeof AuthenticatedPortalDefermentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/change-password': {
      id: '/_authenticated/portal/change-password'
      path: '/portal/change-password'
      fullPath: '/portal/change-password'
      preLoaderRoute: typeof AuthenticatedPortalChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedPortalChangePasswordRoute: typeof AuthenticatedPortalChangePasswordRoute
  AuthenticatedPortalDefermentRoute: typeof AuthenticatedPortalDefermentRoute
  AuthenticatedPortalExamCardRoute: typeof AuthenticatedPortalExamCardRoute
  AuthenticatedPortalFeeStatementRoute: typeof AuthenticatedPortalFeeStatementRoute
  AuthenticatedPortalFeesPaymentRoute: typeof AuthenticatedPortalFeesPaymentRoute
  AuthenticatedPortalFeesPaymentPdfRoute: typeof AuthenticatedPortalFeesPaymentPdfRoute
  AuthenticatedPortalGraduationClearanceRoute: typeof AuthenticatedPortalGraduationClearanceRoute
  AuthenticatedPortalLinkProfileRoute: typeof AuthenticatedPortalLinkProfileRoute
  AuthenticatedPortalProvisionalResultsSlipRoute: typeof AuthenticatedPortalProvisionalResultsSlipRoute
  AuthenticatedPortalProvisionalTranscriptRoute: typeof AuthenticatedPortalProvisionalTranscriptRoute
  AuthenticatedPortalRegisterUnitsRoute: typeof AuthenticatedPortalRegisterUnitsRoute
  AuthenticatedPortalResitExamsRoute: typeof AuthenticatedPortalResitExamsRoute
  AuthenticatedPortalSpecialExamRegistrationRoute: typeof AuthenticatedPortalSpecialExamRegistrationRoute
  AuthenticatedPortalWithdrawalRoute: typeof AuthenticatedPortalWithdrawalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedPortalChangePasswordRoute:
    AuthenticatedPortalChangePasswordRoute,
  AuthenticatedPortalDefermentRoute: AuthenticatedPortalDefermentRoute,
  AuthenticatedPortalExamCardRoute: AuthenticatedPortalExamCardRoute,
  AuthenticatedPortalFeeStatementRoute: AuthenticatedPortalFeeStatementRoute,
  AuthenticatedPortalFeesPaymentRoute: AuthenticatedPortalFeesPaymentRoute,
  AuthenticatedPortalFeesPaymentPdfRoute:
    AuthenticatedPortalFeesPaymentPdfRoute,
  AuthenticatedPortalGraduationClearanceRoute:
    AuthenticatedPortalGraduationClearanceRoute,
  AuthenticatedPortalLinkProfileRoute: AuthenticatedPortalLinkProfileRoute,
  AuthenticatedPortalProvisionalResultsSlipRoute:
    AuthenticatedPortalProvisionalResultsSlipRoute,
  AuthenticatedPortalProvisionalTranscriptRoute:
    AuthenticatedPortalProvisionalTranscriptRoute,
  AuthenticatedPortalRegisterUnitsRoute: AuthenticatedPortalRegisterUnitsRoute,
  AuthenticatedPortalResitExamsRoute: AuthenticatedPortalResitExamsRoute,
  AuthenticatedPortalSpecialExamRegistrationRoute:
    AuthenticatedPortalSpecialExamRegistrationRoute,
  AuthenticatedPortalWithdrawalRoute: AuthenticatedPortalWithdrawalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
